@extends('prssystem.layouts.page')
@section('content')
    <div class="container">
      
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading"><b>About Us</b></div>
                    <div class="panel-body">
                        <p>
                            This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
