@extends('prssystem.layouts.page')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading"><b>Terms And Condition for Use Of www.go4shop.online</b></div>
                    <div class="panel-body">
                        <p>
                            This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
                        </p>
                        <br/>

                        <p>
                            This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of <b>www.go4shop.online</b>.
                        </p>
                        <p> <b>Membership Eligibility</b> </p>
                        <p> 
                            Minimum Age required for membership should be 18 years old. For the use of the Website is available only to persons who can form legally binding contracts under Indian Contract Act, 1872. Persons who are "incompetent to contract" within the meaning of the Indian Contract Act, 1872 including minors, un-discharged insolvents etc. are not eligible to use the Website. 
                            <br>
                            If you are a minor i.e. under the age of 18 years, you shall register on <b>www.go4shop.online</b> as you wish, to use or transaction on website, such use or transaction may be made by your legal guardian or parents on the Website. <b>www.go4shop.online</b> reserves the right to terminate your membership and / or refuse to provide you with access to the Website.
                        </p>


                        <p> <b>About Your Account and Registration</b></p>
                        <p>                            
                            If You using this website i.e <b>www.go4shop.online</b>, We are the responsible for maintaining the confidentiality of your Displaying Name and Password and  Email Address, You shall be responsible for all activities that occur under your Display Name and Password and Email Address. 
                        </p>
                        <p>    
                            Here You agree that if You provide any information that is incomplete or We have found that suspect such information is untrue, inaccurate, not current or incomplete, or not in accordance with the this Terms and conditions, We have the right to indefinitely suspend or terminate or block your account of your membership on the Website <b>www.go4shop.online</b>.
                        </p>
                        <p>
                            Your mobile phone number and/or e-mail address is treated as Your primary identifier on the Website. It is your responsibility to ensure that Your mobile phone number and your email address is up to date on the Website at all times. You agree to notify Us promptly if your mobile phone number or e-mail address changes by updating the same on the Website through a onetime password verification.
                        </p>
                        <p>
                            You agree that Flipkart shall not be liable or responsible for the activities or consequences of use or misuse of any information that occurs under your display name in cases where You have failed to update Your revised mobile phone number and/or e-mail address on the Website.
                        </p>


                        <p> <b>Communications with Members</b></p>Charges
                        <p>Here You agree that we can communicate for send emails or other data, information or communication with you via Email and Message (SMS), We may communicate with you by Call as well</p>


                        <p> <b>Charges</b></p>
                        <p>There is no charge for 'Normal User' use of www.go4shop.online, Charges apply for only <b>Seller</b>, who will sell their products on <b>www.go4shop.online</b> user our supervision that will mutual agreement with Seller and Website.</p>


                        <p><b>Privacy</b></p>
                        <p>
                        We view protection of Your privacy as a very important principle. We understand clearly that You and Your Personal Information is one of Our most important assets. We store and process Your Information including any sensitive financial information collected (as defined under the Information Technology Act, 2000), if any, on computers that may be protected by physical as well as reasonable technological security measures and procedures in accordance with Information Technology Act 2000 and Rules there under. Our current Privacy Policy is available at Privacy. If You object to Your Information being transferred or used in this way please do not use Website.
</p>
<p>
                        We may share personal information with our other corporate entities and affiliates. These entities and affiliatesmay market to you as a result of such sharing unless you explicitly opt-out.
</p>
<p>
                        We may disclose personal information to third parties. This disclosure may be required for us to provide youaccess to our Services, to comply with our legal obligations, to enforce our User Agreement, to facilitate our marketing and advertising activities, or to prevent, detect, mitigate, and investigate fraudulent or illegal activities related to our Services. We do not disclose your personal information to third parties for their marketing and advertising purposes without your explicit consent.
</p>
<p>
                        We may disclose personal information if required to do so by law or in the good faith belief that such disclosure is reasonably necessary to respond to subpoenas, court orders, or other legal process. We may disclose personal information to law enforcement offices, third party rights owners, or others in the good faith belief that such disclosure is reasonably necessary to: enforce our Terms or Privacy Policy; respond to claims that an advertisement, posting or other content violates the rights of a third party; or protect the rights, property or personal safety of our users or the general public.
</p>
<p>
                        We and our affiliates will share / sell some or all of your personal information with another business entity should we (or our assets) plan to merge with, or be acquired by that business entity, or re-organization, amalgamation, restructuring of business. Should such a transaction occur that other business entity (or the new combined entity) will be required to follow this privacy policy with respect to your personal information.
                        </p>



                        <p><b>Selling On Website</b></p>
                        <p>
                            You Registered as Seller on the website (<b>www.go4shop.online</b>), you are allowed to list item(s) for sale on the Website in accordance with the Policies which are incorporated by way of reference in this Terms of Use. 
                        </p>
                        <p>
                            You must be legally able to sell the item(s) you list for sale on our Website. You must ensure that the listed items do not infringe upon the intellectual property, trade secret or other proprietary rights or rights of publicity or privacy rights of third parties. Listings may only include text descriptions, graphics and pictures that describe your item for sale. All listed items must be listed in an appropriate category on the Website. All listed items must be kept in stock for successful fulfilment of sales.
                        </p>
                        <p>
                            The listing description of the item must not be misleading and must describe actual condition of the product. If the item description does not match the actual condition of the item, you agree to refund any amounts that you may have received from the User(Buyer). You agree not to list a single product in multiple quantities across various categories on the Website. <b>wwww.go4shop.online</b> reserves the right to delete such multiple listings of the duplicate products listed.
                        </p>

                        </p>

                        <p><b>Payments Options</b></p>
                        <p>You, as a Buyer, understand that upon initiating a Transaction You are entering into a legally binding and enforceable contract with the Seller to purchase the products and /or services from the Seller using the Payment Facility, and You shall pay the Transaction Price through Your Issuing Bank to the Seller using Payment Facility.
                        </p>
                        <p>
                        You, as a Buyer, may agree with the Seller through electronic communication and electronic records and using the automated features as may be provided by Payment Facility on any extension / increase in the Dispatch and/or Delivery time and the Transaction shall stand amended to such extent. Any such extension / increase of Dispatch / Delivery time or subsequent novation / variation of the Transaction should be in compliance with Payment Facility Rules and Policies.
                        </p>
                        <p>
                        You, as a Buyer, shall electronically notify Payment Facility using the appropriate Flipkart Website features immediately upon Delivery or non Delivery within the time period as provided in Policies. Non notification by You of Delivery or non Delivery within the time period specified in the Policies shall be construed as a deemed Delivery in respect of that Transaction. In case of Cash On Delivery transactions, Buyer is not required to confirm the receipt of products or services.
                        </p>
                        <p>
                        You, as a Buyer, shall be entitled to claim a refund of the Transaction Price (as Your sole and exclusive remedy) in case You do not receive the Delivery within the time period agreed in the Transaction or within the time period as provided in the Policies, whichever is earlier. In case you do not raise a refund claim using Website features within the stipulated time than this would make You ineligible for a refund.
                        </p>

                        <p>
                        
                        You, as a Buyer, understand that the Payment Facility may not be available in full or in part for certain category of products and/or services and/or Transactions as mentioned in the Policies and hence You may not be entitled to a refund in respect of the Transactions for those products and /or services
                        </p>

                        <p>
                        Except for Cash On Delivery transaction, refund, if any, shall be made at the same Issuing Bank from where Transaction Price was received, or through any other method available on the Website, as chosen by You.
                        </p>
                            
                        <p>    
                        For Cash On Delivery transactions, refunds might be cash mode or it can be made via electronic payment transfers.<br/>

                        Refund shall be made in Indian Rupees only and shall be equivalent to the Transaction Price received in Indian Rupees.<br/>

                        For electronics payments, refund shall be made through payment facility using NEFT / RTGS or any other online banking / electronic funds transfer system approved by Reserve Bank India (RBI).<br/>

                        Refunds may be supported for select banks. Where a bank is not supported for processing refunds, You will be required to share alternate bank account details with us for processing the refund.<br/>

                        Refund shall be conditional and shall be with recourse available to Flipkart in case of any misuse by Buyer.<br/>

                        We may also request you for additional documents for verification.
                        </p>
                        <center><p>*****************************Ends********************************</p></center>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
